### PR TITLE
Pr

### PR DESCRIPTION
**Pull request by bermanjosh**

### CODE REVIEW

**Comment by bermanjosh** [comment]
Hi @meteficha, 

Can you look this over for Yesod 1.4? The `cabal.config` is mainly to force using the installed `network`, as `network-2.6` can't be built directly on Windows, so anyone using HP 2013.2 would have problems.

Thanks

**Comment by bermanjosh** [comment]
Yesod tries to build with `network 2.6` which can't be compiled on Windows; so the build will fail on a Windows machine running HP 2013.2 (which shipped with `network 2.5`). The `entropy < 0.3.3` was because `entropy 0.3.3` wouldn't compile, and `0.3.2` did.

**Comment by meteficha** [comment]
If this `cabal.config` file meant to be exported to Hackage or only for local development?

Regarding the `network` package, I wonder if this is the right place to state this constraint.  For example, shouldn't [yesod-core](https://github.com/yesodweb/yesod/tree/master/yesod-core) have the same constraint on a `cabal.config` then?

Regarding `entropy`, my worries are wrt newer versions.  Actually, `entropy` is already at `0.3.4.1`.  Shouldn't it read `entropy < 0.3.3 || >= 0.3.4` then?

**Comment by bermanjosh** [comment]
I guess I don't really know - what's the normal community convention? Is the responsibility of the user to set these sort of package constraints to fit into their specific system? Or the package maintainer to try to make the package as compatible as possible? I don't exactly have a ton of experience here, so I don't really know. Obviously whatever you think.

Regarding `entropy` - yes. The issue I was having building was fixed in `0.3.4.1`. 

Should I just drop the whole `cabal.config`?

**Comment by meteficha** [comment]
I have zero experience with releasing packages with `cabal.config` files, that's why I'm asking you about its purpose :).  If it works without it, perhaps it would be best dropping it.

**Comment by bermanjosh** [comment]
@meteficha 
I removed the cabal.config file. Can we merge now? Thanks.

**Comment by meteficha** [comment]
Thanks, released!  Sorry for the delay.

**Pull request merged**
